server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://140.238.187.194:3100/loki/api/v1/push

scrape_configs:
  - job_name: fastapi_logs
    static_configs:
      - targets:
          - localhost
    pipeline_stages:
      - match:
          selector: '{job="fastapi"}'
        stages:
          - regex:
              expression: '^(?P<timestamp>.*?)\s+(?P<level>[A-Z]+)\s+\[(?P<logger>[^\]]+)\]\s+-\s+(?P<message>.*)$'
